name: CI con gradle

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: 'github'
          settings-path: ${{github.workspace}}
      - name: set up gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 2.1
            
        #### Builds
      - name: hacer build del frontend 
        run: ./gradle/build
        working-directory: src/clients
         
          
      - name: hacer build del backend
        run: ./gradle/build test
        working-directory: src/clients
          
            
          
