name: CI con gradle

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: 'github'
          settings-path: ${{github.workspace}}
      - name: set up gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 2.1
            
        #### Builds
      - name: hacer build del frontend 
        run: ./gradlew build
        working-directory: src/Clients
         
          
      - name: hacer build del backend
        run: ./gradlew build test
        working-directory: src/Backend/OrderService
      
      - name: dockerizar el front y el backend
        run: |
          cp src/Clients/build/libs/*.war deploy/docker/Clients/drop
          docker build -t p2gps/web deploy/docker/Clients
          cp src/Backend/OrderService/build/libs/ordering* deploy/docker/Order/drop
          docker build -t p2gps/order deploy/docker/Order
          
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Etiquetar con formato DockerHub
        run: |
          docker tag p2gps/web ${{secrets.DOCKERHUB_USERNAME}}/p2pgs:web
          docker tag p2gps/order ${{secrets.DOCKERHUB_USERNAME}}/p2pgs:order
      - name: Push a DockerHub
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/p2gps:web
          docker push ${{secrets.DOCKERHUB_USERNAME}}/p2gps:order
          
            
          
