name: CI con gradle

on:
  push:
    branches: [master]
  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      permission:
        contents: read
        packages: write
        
      steps:
        - uses: action/checkout@v2
        - name: Set up JDK 8
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'adopt'
            server-id: 'github'
            settings-path: ${{github.workspace}}
        - name: set up gradle
          uses: gradle/gradle-build-action@v2
          with:
            gradle-version: 2.1
            
        #### Builds
        - name: hacer build del frontend 
          run:
            working-directory:src/clients
           ./gradle/build
          
        - name: hacer build del backend
          run:
            working-directory:src/clients
            ./gradle/build test
            
          
